# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample
  name: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample
    spec:
      containers:
        - image: lalitkathuria/spring-kubernetes
          name: spring-kubernetes
          resources: {}
          ports:
            - containerPort: 8181
          imagePullPolicy: Always
status: {}
