# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample
  name: sample
spec:
  ports:
    - name: 8181-8181
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: sample
  type: ClusterIP
status:
  loadBalancer: {}